import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import { Providers } from './components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gabriel Santos | Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressContentEditableWarning>
      <body
        className={` ${inter.className} bg-white text-black dark:bg-black dark:selection:bg-black dark:text-white h-full selection:bg-gray-50 transtion duration-300`}
      >
        <Providers>
          <Navbar />
          <main className='max-w-5xl mx-auto px-4 sm:px-6 lg:px-8'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
